spring:
  application:
    name: VolunteerHub
  datasource:
    url: jdbc:postgresql://localhost:5432/volunteer_hub
    username: postgres
    password: 1382005a
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /
jwt:
  signerKey: "V6MwVJfHlK1qrOBkjgcc5r4MYr4cLU74mnoL+kz5WEhPAIVQkw16Yo269Tkma26s"
  valid-duration: 36000 # in seconds
  refreshable-duration: 36000
cloudinary:
  cloud-name: "dcvrdyzo1"
  api-key: 589483672795972
  api-secret: ${API_SECRET}